#!/bin/bash

cd /tmp/sackfigurator
HTML="<html><head><title>Undelegated Domains</title></head><body><h1>Undelegated Domains</h1>"
for f in * 
do 
  FILEHTML="<h2>${f}</h2>"
  LINE="<table border=1><thead><th>zone</th><th>GoogleDNS</th><th>Zone NS</th></thead><tbody>"
  COUNT=0
  for r in $(grep ^dns ${f} | awk '{ print $2 }' | sort | uniq) 
  do  
    NSNET=$(dig +short ns @8.8.8.8 ${r}) 
    if [ $(echo ${NSNET} | grep -ci nameserver.net) -eq 0 ]
    then 
      COUNT=1
      LINE="${LINE}<tr><td>${r}</td><td>"
      if [ $(echo ${NSNET} | grep -v ^$ | wc -l) -eq 0 ]
      then
        LINE="${LINE}NO NS RECORDS</td><td>NO NS RECORDS</td></tr>"
      else
        for z in ${NSNET}
        do
          LINE="${LINE}${z}<br>"
        done
        LINE="${LINE}</td><td>"
        LINE="${LINE}$(for z in ${NSNET}
          do
            ZDNS=$(dig +short ns @${z} ${r})
            for n in ${ZDNS}
            do
              echo ${n}
            done
          done | sort | uniq | tr ' ' '<br>')"
        LINE="${LINE}</td></tr>\n"
      fi  
    fi
  done
  LINE="${LINE}</tbody></table>\n"
  if [ ${COUNT} -gt 0 ]
  then
    FILEHTML="${FILEHTML}${LINE}"
  fi
  HTML="${HTML}${FILEHTML}"
done
echo -e "${HTML}</body></html>" 